# Site settings
title: Sergey Evstifeev
theme: "In The Works"
description: > # this means to ignore newlines until "baseurl:"
  Sergey Evstifeev's personal blog
baseurl: ""
url: "http://sergeyevstifeev.com"
twitter_username: sergeyevstifeev
github_username:  sergeyevstifeev
avatar: images/avatar.jpeg
header-img: images/sky.jpeg
paginate: 5

# Build settings
markdown: kramdown
